# Jekyll configuration
title: XWordList
author:
  name: Andrew Anker
  email: "aa@quid.pro"
description:  Documentation site for XWordList software
description: >
  Documentation site for XWordList, software to help create, build and
  organize crossword puzzle word lists.

url: "https://xwl.com"
markdown: GFM

# Theme info
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    github: aanker/xwordlist
    facebook: aanker
    linkedin: aanker
    twitter: aa

header_pages:
  - help.md
  - resources.md
plugins:
  - jekyll-feed
