# Jekyll configuration
title: XWordList
author:
  name: Andrew Anker
  email: "aa@quid.pro"
  url: https://quid.pro/xwords
description: >
  Documentation site for XWordList, software to help create, build and
  organize crossword puzzle word lists.

url: "https://xwl.ist"
markdown: GFM

# Theme info
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
  - { platform: github,          user_url: "https://github.com/aanker" }
  - { platform: facebook,          user_url: "https://facebook.com/aanker" }
  - { platform: linkedin,          user_url: "https://www.linkedin.com/in/aanker/" }
  - { platform: twitter,          user_url: "https://twitter.com/aa" }

header_pages:
  - help.md
  - resources.md
plugins:
  - jekyll-feed

collections:
  recipes:
    output: true