# Jekyll configuration
title: XWordList
author:
  name: Andrew Anker
  email: "aa@quid.pro"
description:  Documentation site for XWordList software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xwl.com"
markdown: GFM

# Theme info
theme: minima
minima:
  skin: auto
  social_links:
    github: aanker
    facebook: aanker
    linkedin: aanker
    twitter: aa

header_pages:
  - help.md
plugins:
  - jekyll-feed
